version: "3.1"
services:
  redis:
    image: "redis:alpine"
  mongo:
    image: "mongo:3.4-xenial"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: eclogue
      MONGO_INITDB_DATABASE: eclogue
    expose:
      - 27017
  web:
    build: .
    environment:
      - ENV=docker
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    command: python manage.py bootstrap --username:admin --password=eclogue && python manage.py start
