routes = {
    'Job': [
        '/jobs/preview/inventory',
        '/jobs',
        '/jobs',
        '/jobs/<_id>',
        '/jobs/<_id>',
        '/jobs/<_id>/tasks',
        '/jobs/runner/doc',
        '/jobs/runner/module',
        '/execute',
    ],
    'Playbook': [
        '/playbook/edit/<_id>',
        '/playbook/rename/<_id>',
        '/playbook/upload',
        '/playbook/folder',
        '/playbook/setup',
        '/playbook/galaxy',
        '/playbook/tags',
        '/playbook/<_id>/file',
        '/playbook/<_id>/file',
    ],
    'Task': [
        '/tasks'
        '/tasks/queue',
    ],
    'Dashboard': [
        '/dashboard'
    ],
    'Configuration': [
        '/configurations',
        '/configurations/<_id>',
        '/configurations',
        '/configurations/list/ids',
    ],
    'Books': [
        '/books/all',
        '/books',
        '/books/<_id>',
        '/books/<_id>',
        '/books',
        '/books/<_id>/playbook',
        '/books/<_id>/download',
        '/books/<_id>/playbook',
        '/books/<_id>/entries',
        '/books/<name>/inventory',
        '/books/<_id>/roles',
    ],
    'Resource': [
        '/cmdb/regions',
        '/cmdb/regions',
        '/cmdb/regions/<_id>',
        '/cmdb/groups',
        '/cmdb/groups',
        '/cmdb/groups/<_id>',
        '/cmdb/inventory',
        '/apps',
        '/apps',
        '/devices/add',
        '/devices',
        '/devices/<_id>',
    ],
    'Credential': [
        '/credentials',
        '/credentials',
        '/credentials/_id',
    ],
    'Team': [
        '/teams',
        '/teams',
        '/teams/<_id>',
        '/teams/members',
        '/roles',
        '/roles',
        '/users',
        '/users/<user_id>/roles',
        '/menus',
    ],
    'Default': [
        '/search/users',
        '/login',
        '/users/<_id>',
        '/users/roles',
        '/menus',
        '/notifications',
        '/notifications/read',
    ],
}
