version: "3.1"
services:
  redis:
    image: "redis:alpine"
    ports:
        - "6379:6379"
  mongo:
    image: "mongo:3.4-xenial"
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: eclogue
#      MONGO_INITDB_DATABASE: eclogue
#      MONGO_AUTH_SOURCE: admin
    ports:
      - "27017:27017"
