project: linger
author: shisang
email: adming@admin.com
repo: https://github.com
home_path: {{ home_path }}
log:
  eclogue: {{ home_path }}/storage/logs
  ansible: {{ home_path }}/storage/logs
logging:
  version: 1
  loggers:
    eclogue:
      level: DEBUG
      handlers:
        - file
        - console
        - mongo
    console:
      level: DEBUG
      handlers:
        - console
        - consoleError
  handlers:
    mongo:
      (): eclogue.lib.logger.MongoHandler
      level: INFO
      formatter: mongo
      filters:
        - requestId
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
    consoleError:
      class: logging.StreamHandler
      level: ERROR
      formatter: simple
      stream: ext://sys.stderr
    file:
      class: logging.handlers.RotatingFileHandler
      filename: {{ home_path }}/storage/logs/eclogue.log
      level: DEBUG
#      progarate: yes
  root:
    level: DEBUG
    handlers:
      - console
      - consoleError
  formatters:
    simple:
      formate: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    mongo:
      (): eclogue.lib.logger.MongoFormatter
  filters:
    requestId:
      (): flask_log_request_id.RequestIDLogFilter
workspace:
  tmp: {{ home_path }}/storage/tmp
  playbook: {{ home_path }}/storage/tmp
  base_dir: {{ home_path }}/storage/eclogue
  job: {{ home_path }}/storage/eclogue/job
  build: {{ home_path }}/storage/eclogue/job
jenkins:
  default:
    base_url: xx
    username: xx
    password: xx
gitlab:
  token: xx
  base_url: https://gitlab.com
vault:
  secret: xx

mongodb:
  uri: 'mongodb://root:password@localhost/?authSource=admin&authMechanism=SCRAM-SHA-1'
  db: 'eclogue'
jwt:
  key: '2:sha256:50000$testset'
  iss: 'https://devops.eclogueio.com'
  aud: 'https://eclogueio.com'
  header:
    alg: 'HS256'
redis:
  conn:
    host: localhost
    port: 6379
    decode_responses: !!bool "true"
