project: eclogue
author: shisang
email: mulberry10th@gmail.com
repo: https://github.com/eclogue/eclogue
home_path: {{ home_path }}
dommain: "http://localhost:5001"
debug: true
log:
  eclogue: {{ home_path }}/storage/logs
  ansible: {{ home_path }}/storage/logs
logging:
  version: 1
  loggers:
    file:
      level: DEBUG
      handlers:
        - file
    eclogue:
      level: INFO
      handlers:
        - file
        - mongo
    console:
      level: DEBUG
      propagate: 0
      handlers:
        - console
  handlers:
    mongo:
      (): eclogue.log.handler.MongoHandler
      level: INFO
      formatter: mongo
      filters:
        - requestId
    file:
      class: logging.handlers.RotatingFileHandler
      filename: {{ home_path }}/storage/logs/eclogue.log
      level: DEBUG
    console:
      (): eclogue.log.handler.ConsoleHandler
      level: DEBUG
    default:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  formatters:
    simple:
      formate: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
    mongo:
      (): eclogue.log.formatter.MongoFormatter
  filters:
    requestId:
      (): flask_log_request_id.RequestIDLogFilter
  root:
    level: INFO
    handlers:
      - file
workspace:
  tmp: {{ home_path }}/storage/tmp
  playbook: {{ home_path }}/storage/tmp
  base_dir: {{ home_path }}/storage/eclogue
  job: {{ home_path }}/storage/eclogue/jobs
  build: {{ home_path }}/storage/eclogue/builds
vault:
  secret: xx

mongodb:
  uri: 'mongodb://localhost:27017'
  db: 'eclogue'
jwt:
  key: '2:sha256:50000$testset'
  iss: 'https://devops.eclogueio.com'
  aud: 'https://eclogueio.com'
  header:
    alg: 'HS256'
  exp: 604800
redis:
  conn:
    host: localhost
    port: 6379
    decode_responses: !!bool "true"

task:
  history: 50
  always_eager: false

api:
  prefix: ''
  force_check_binding: true
