TESTING: True
mongodb:
  uri: 'mongodb://root:sfeeawgeshr6u5w12z@193.112.127.136:27017/?authSource=admin&authMechanism=SCRAM-SHA-1'
  db: 'eclogue'
jwt:
  key: '2:sha256:50000$testset'
  iss: 'http://devops.upward.com'
  aud: 'http://upward.com'
  header:
    alg: 'HS256'
redis:
  conn:
    host: localhost
    port: 6379
    decode_responses: !!bool "true"

jenkins:
  default:
    base_url: http://jks.sangsay.com/
    username: eclogue
    password: wei123.01
gitlab:
  token: R7T1-ar5SWiu7ysRLzjY
  base_url: https://gitlab.com
vault:
  secret: abcdefgadfk@#cda4dfaf9xF)d
